grammar::= syntax_definition lexical_definition? EOF

syntax_definition ::= (rule | comment)*

rule ::= identifier "=" expression ";"

expression ::= term ("|" term)*

term ::= factor ("," factor)*

factor ::= (integer "*")? primary

primary ::= identifier
          | terminal
          | optional
          | repetition
          | group
          | char_range

optional   ::= "[" expression "]"
repetition ::= "{" expression "}"
group      ::= "(" expression ")"

char_range ::= hex_number ".." hex_number

comment ::= "(*" (character | whitespace)* "*)" 

lexical_definition ::= "%TOKENS%" (rule | comment)*

whitespace
         ::= whitespace^token
          /* ws: definition */

<?TOKENS?>

identifier ::= letter (letter | digit | "_")*

terminal ::= '"' terminal_character* '"'

terminal_character ::= (character - '"') | whitespace

character ::= [#x21-#xD7FF]
            | [#xE000-#xFFFD]
            | [#x10000-#x10FFFF]

integer ::= digit digit*

letter ::= "A" | "B" | "C" | "D" | "E" | "F" | "G"
         | "H" | "I" | "J" | "K" | "L" | "M" | "N"
         | "O" | "P" | "Q" | "R" | "S" | "T" | "U"
         | "V" | "W" | "X" | "Y" | "Z"
         | "a" | "b" | "c" | "d" | "e" | "f" | "g"
         | "h" | "i" | "j" | "k" | "l" | "m" | "n"
         | "o" | "p" | "q" | "r" | "s" | "t" | "u"
         | "v" | "w" | "x" | "y" | "z" 

digit ::= "0" | "1" | "2" | "3" | "4"
        | "5" | "6" | "7" | "8" | "9" 

hex_number ::= "#" hex_char*
hex_char ::= digit | "A" | "B" | "C" | "D" | "E" | "F"

whitespace ::= [#x9#xA#xD#x20]+ 

EOF ::= $