grammar = syntax_definition, [ lexical_definition ] ;

syntax_definition = { syntax_rule | comment } ;

syntax_rule = metaa_identifier, "=", definition_list, ";" ;

definition_list = single_definition, { "|", single_definition } ;
single_definition = term ,{ ",", term } ;
term = factor, { "-", exception } ;
exception = factor ;
factor = [ integer, "*" ], primary ;

primary = metaa_identifier
        | terminal_string
        | optional_sequence
        | repeted_sequence
        | grouped_sequence
        | character_definition ;

optional_sequence = "[", definition_list, "]" ;
repeted_sequence = "{", definition_list, "}" ;
grouped_sequence = "(", definition_list, ")" ;

character_definition = hexadecimal_number | character_range ;
character_range = hexadecimal_number, "..", hexadecimal_number ;

comment = "(*", { character | space  }, "*)" ;

lexical_definition = "%TOKENS%", { syntax_rule | comment } ;

%TOKENS%

metaa_identifier = letter, { letter | decimal_digit | "_" } ;

terminal_string = single_quote_terminal_string | double_quote_terminal_string ;
single_quote_terminal_string = "'", { single_quote_terminal_character }, "'" ;
double_quote_terminal_string = '"', { double_quote_terminal_character }, '"' ;

single_quote_terminal_character = character - #27 | whitespace ;
double_quote_terminal_character = character - #22 | whitespace ;

character = #0 .. #FFFF - ( #9 | #A | #D | #20 ) ;

integer = decimal_digit, { decimal_digit } ;

letter = "A" | "B" | "C" | "D" | "E" | "F" | "G"
       | "H" | "I" | "J" | "K" | "L" | "M" | "N"
       | "O" | "P" | "Q" | "R" | "S" | "T" | "U"
       | "V" | "W" | "X" | "Y" | "Z"
       | "a" | "b" | "c" | "d" | "e" | "f" | "g"
       | "h" | "i" | "j" | "k" | "l" | "m" | "n"
       | "o" | "p" | "q" | "r" | "s" | "t" | "u"
       | "v" | "w" | "x" | "y" | "z" ;

decimal_digit = "0" | "1" | "2" | "3" | "4"
              | "5" | "6" | "7" | "8" | "9" ;

hexadecimal_number = "#", { hexadecimal_character } ;
hexadecimal_character = decimal_digit
                      | "A" | "B" | "C" | "D" | "E" | "F"
                      | "a" | "b" | "c" | "d" | "e" | "f" ;

whitespace = #9 | #A | #D | #20 ;
