(* Test syntax *)
syntax = { rule | directive | comment | space } ;

rule = meta-identifier , defining-symbol , definitions-list , terminator-symbol ;

%TOKENS%

defining-symbol = '=' ;
terminator-symbol = ';' ;

%RULES%

meta-identifier = letter , { meta-identifier-character } ;
letter = #41..#5A | #61..#7A ;