(* Test syntax *)
syntax = { rule | directive | comment | space } ;

rule = meta_identifier , defining_symbol , definitions_list , terminator_symbol ;

%TOKENS%

defining_symbol = '=' ;
terminator_symbol = ';' ;
concatenate_symbol = ',' ;
definition_separator_symbol = '|' ;
except_symbol = '-' ;
repetition_symbol = '*' ;
range_symbol = '..' ;
hex_prefix = '#' ;
directive_symbol = '%' ;
first_quote_symbol = "'" ;
second_quote_symbol = '"' ;
special_sequence_symbol = '?' ;
start_option_symbol = '[' ;
end_option_symbol = ']' ;
start_repeat_symbol = '{' ;
end_repeat_symbol = '}' ;
start_group_symbol = '(' ;
end_group_symbol = ')' ;
start_comment_symbol = '(*' ;
end_comment_symbol = '*)' ;

meta_identifier = letter , { meta_identifier_character } ;
letter = 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | 'H' | 'I' | 'J' 
       | 'K' | 'L' | 'M' | 'N' | 'O' | 'P' | 'Q' | 'R' | 'S' | 'T' 
       | 'U' | 'V' | 'W' | 'X' | 'Y' | 'Z' 
       | 'a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'g' | 'h' | 'i' | 'j' 
       | 'k' | 'l' | 'm' | 'n' | 'o' | 'p' | 'q' | 'r' | 's' | 't' 
       | 'u' | 'v' | 'w' | 'x' | 'y' | 'z' ;

decimal_digit = '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' ;